env:
   global:
     - CONAN_BUILD_REQUIRES=android_ndk_installer/r20@bincrafters/stable,android-sdk/26.1.1@tereius/stable
     - CONAN_REMOTES=https://api.bintray.com/conan/tereius/public-conan@True@tereius
     - CONAN_OPTIONS="qt:openssl=False,qt:opengl=es2,qt:with_harfbuzz=False,qt:with_pq=False,qt:with_mysql=False,qt:with_pcre2=False,qt:with_glib=False,qt:with_libjpeg=False,qt:with_libpng=False,qt:with_odbc=False,qt:with_sdl2=False,qt:with_libalsa=False,qt:with_openal=False"
     - CONAN_CLANG_VERSIONS=8

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"

matrix:
   include:
      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=21
      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=21

      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=21
      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=21

      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=21
      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=21

      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=21
      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=21

      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=22
      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=22

      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=22
      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=22

      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=22
      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=22

      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=22
      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=22

      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=23
      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=23

      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=23
      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=23

      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=23
      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=23

      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=23
      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=23

      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=24
      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=24

      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=24
      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=24

      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=24
      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=24

      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=24
      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=24

      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=26
      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=26

      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=26
      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=26

      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=26
      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=26

      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=26
      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=26

      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=27
      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=27

      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=27
      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=27

      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=27
      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=27

      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=27
      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=27

      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=28
      - <<: *linux
        env:  CONAN_ARCHS="x86_64" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=28

      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=28
      - <<: *linux
        env:  CONAN_ARCHS="x86" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=28

      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=28
      - <<: *linux
        env:  CONAN_ARCHS="armv7" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=28

      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=1 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=28
      - <<: *linux
        env:  CONAN_ARCHS="armv8" CONAN_CURRENT_PAGE=2 CONAN_TOTAL_PAGES=2 ANDROID_API_LEVEL=28

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh
script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh | cat