build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_TOTAL_PAGES: 6

    matrix:
        - CONAN_BUILD_REQUIRES: android_ndk_installer/r20@bincrafters/stable,android-sdk/26.1.1@tereius/stable
          CONAN_REMOTES: https://api.bintray.com/conan/tereius/public-conan@True@tereius
          CONAN_OPTIONS: "qt:openssl=False,qt:opengl=es2,qt:with_harfbuzz=False,qt:with_pq=False,qt:with_mysql=False,qt:with_pcre2=False,qt:with_glib=False,qt:with_libjpeg=False,qt:with_libpng=False,qt:with_odbc=False,qt:with_sdl2=False,qt:with_libalsa=False,qt:with_openal=False,qt:with_sqlite3=False"
          CONAN_CLANG_VERSIONS: 8
          CONAN_ARCHS: x86
          ANDROID_API_LEVEL: 28
          CONAN_ENV_COMPILER: clang
        - CONAN_BUILD_REQUIRES: android_ndk_installer/r20@bincrafters/stable,android-sdk/26.1.1@tereius/stable
          CONAN_REMOTES: https://api.bintray.com/conan/tereius/public-conan@True@tereius
          CONAN_OPTIONS: "qt:openssl=False,qt:opengl=es2,qt:with_harfbuzz=False,qt:with_pq=False,qt:with_mysql=False,qt:with_pcre2=False,qt:with_glib=False,qt:with_libjpeg=False,qt:with_libpng=False,qt:with_odbc=False,qt:with_sdl2=False,qt:with_libalsa=False,qt:with_openal=False,qt:with_sqlite3=False"
          CONAN_CLANG_VERSIONS: 8
          CONAN_ARCHS: x86_64
          ANDROID_API_LEVEL: 28
          CONAN_ENV_COMPILER: clang
        - CONAN_BUILD_REQUIRES: android_ndk_installer/r20@bincrafters/stable,android-sdk/26.1.1@tereius/stable
          CONAN_REMOTES: https://api.bintray.com/conan/tereius/public-conan@True@tereius
          CONAN_OPTIONS: "qt:openssl=False,qt:opengl=es2,qt:with_harfbuzz=False,qt:with_pq=False,qt:with_mysql=False,qt:with_pcre2=False,qt:with_glib=False,qt:with_libjpeg=False,qt:with_libpng=False,qt:with_odbc=False,qt:with_sdl2=False,qt:with_libalsa=False,qt:with_openal=False,qt:with_sqlite3=False"
          CONAN_CLANG_VERSIONS: 8
          CONAN_ARCHS: armv7
          ANDROID_API_LEVEL: 28
          CONAN_ENV_COMPILER: clang
        - CONAN_BUILD_REQUIRES: android_ndk_installer/r20@bincrafters/stable,android-sdk/26.1.1@tereius/stable
          CONAN_REMOTES: https://api.bintray.com/conan/tereius/public-conan@True@tereius
          CONAN_OPTIONS: "qt:openssl=False,qt:opengl=es2,qt:with_harfbuzz=False,qt:with_pq=False,qt:with_mysql=False,qt:with_pcre2=False,qt:with_glib=False,qt:with_libjpeg=False,qt:with_libpng=False,qt:with_odbc=False,qt:with_sdl2=False,qt:with_libalsa=False,qt:with_openal=False,qt:with_sqlite3=False"
          CONAN_CLANG_VERSIONS: 8
          CONAN_ARCHS: armv8
          ANDROID_API_LEVEL: 28
          CONAN_ENV_COMPILER: clang
        - MINGW_CONFIGURATIONS: '4.9@x86@dwarf2@posix'
        - MINGW_CONFIGURATIONS: '4.9@x86_64@seh@posix'
        - MINGW_CONFIGURATIONS: '6@x86@dwarf2@posix'
        - MINGW_CONFIGURATIONS: '6@x86_64@seh@posix'
        - MINGW_CONFIGURATIONS: '7@x86@dwarf2@posix'
        - MINGW_CONFIGURATIONS: '7@x86_64@seh@posix'
        - MINGW_CONFIGURATIONS: '8@x86@dwarf2@posix'
        - MINGW_CONFIGURATIONS: '8@x86_64@seh@posix'
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 6
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 6
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 6
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 6
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Release
          CONAN_CURRENT_PAGE: 6
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 1
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 2
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 3
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 4
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 5
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16
          CONAN_BUILD_TYPES: Debug
          CONAN_CURRENT_PAGE: 6

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
